spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ideas2it
    url: jdbc:mysql://localhost:3306/ideas2it
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 600000
  redis:
    host: localhost
    port: 6379 
