spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ideas2it?createDatabaseIfNotExist=true&autoReconnect=true
    username: root
    password: ideas2it
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 600000
  redis:
    host: localhost
    port: 6379 
com:
 patient:
   service:
    uri: http://localhost:8080/patients
    name: patient-service 
  user:
   service:
    uri: http://localhost:8081/
    name: user-service
 vitalsign:
   service:
    uri: http://localhost:8082/vitalsign
    name: vitalsign-service 
